#conda env update --file environment.yml --prune
name: food_product
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - ipykernel
  - ipywidgets
  - jupyterlab_widgets
  - python<3.10
  - pip
  - tqdm
  - psycopg2
  - SQLAlchemy
  - pandas
  - Pillow
  - fastapi
  - uvicorn
  - pip:
    - --find-links https://download.pytorch.org/whl/torch_stable.html
    - torch==1.10.1+cu113
    - torchvision==0.11.2+cu113
    - transformers
    - tendo
    - dateparser
    - transformers
    - matplotlib
    - plotly
    - ftfy
    - schedule
    - psutil
    - docker
    - wrapt
    - nbdev
    - pyTelegramBotAPI
    - qdrant_client
    - tzwhere