# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"branch": "00_paths.ipynb",
         "bot_token": "00_paths.ipynb",
         "main_path": "00_paths.ipynb",
         "data_path": "00_paths.ipynb",
         "reference_images_path": "00_paths.ipynb",
         "fragment_reference_images_path": "00_paths.ipynb",
         "port": "00_psql.ipynb",
         "engine": "00_psql.ipynb",
         "Session": "00_psql.ipynb",
         "session": "00_psql.ipynb",
         "Base": "00_psql.ipynb",
         "schema": "00_psql.ipynb",
         "LocalBase": "00_psql.ipynb",
         "Foods": "00_psql.ipynb",
         "CFoods": "00_psql.ipynb",
         "FFoods": "00_psql.ipynb",
         "Users": "00_psql.ipynb",
         "Dishes": "00_psql.ipynb",
         "User_properties": "00_psql.ipynb",
         "FoodsP": "00_psql.ipynb",
         "FoodsPI": "00_psql.ipynb",
         "Indexed": "00_psql.ipynb",
         "mean_filter": "00_visual.ipynb",
         "visualize_array": "00_visual.ipynb",
         "extrapolate": "00_visual.ipynb",
         "expand_boundaries": "00_visual.ipynb",
         "crop_center_arr": "00_visual.ipynb",
         "apply_mask": "00_visual.ipynb",
         "crop_zeros": "00_visual.ipynb",
         "crop_image_to_square": "00_visual.ipynb",
         "search_clip": "00_visual.ipynb"}

modules = ["paths.py",
           "psql.py",
           "visual.py"]

doc_url = "https://{user}.github.io/food/"

git_url = "https://github.com/{user}/food/tree/{branch}/"

def custom_doc_links(name): return None
