# AUTOGENERATED! DO NOT EDIT! File to edit: 06_clip.ipynb (unless otherwise specified).

__all__ = ['search_by_text', 'id_table']

# Cell
import pandas as pd
import numpy as np
from .tools import *
from .paths import *
from sqlalchemy import Table,BIGINT,Column
from .clipmodel import text2clip

# Cell
def search_by_text(text,topk=5,parameters={},prompt = None,prompt_factor=3):
    clip = text2clip(text).numpy()
    if prompt:
        prompt_clip = text2clip(prompt+text).numpy()
        diff = prompt_clip - clip
        clip = clip + diff*prompt_factor

    query_expr, v_one_hot = onehot.build_milvus_query(parameters)
    clip = np.hstack([clip, v_one_hot])
    results = search_by_clip(clip, topk,query_expr=query_expr)
    df = get_metadata(results[1])
    df['accuracy'] =results[0]
    try:
        df['url'] = df.apply(lambda x: f"https://away.guru/photos/{get_hash_folder(int(x['id']))}/{int(x['id'])}.jpg",axis=1)
        df['link'] = df['listing_id'].apply(lambda listing_id:f'https://www.airbnb.com/rooms/{listing_id}')
    except:
        df['url']  = np.nan
        df['link'] = np.nan
    return df.drop(columns = ['listing_id','id'])
id_table = Table('ids_meta',Base.metadata,Column('id', BIGINT),extend_existing=True)