# AUTOGENERATED! DO NOT EDIT! File to edit: 00_paths.ipynb (unless otherwise specified).

__all__ = ['mapbox_access_token', 'branch', 'bot_token', 'main_path', 'data_path', 'reference_images_path',
           'fragment_reference_images_path']

# Cell
from pathlib import Path
import os

# Cell
Path.ls = lambda x: list(x.iterdir())

# Cell
mapbox_access_token = 'pk.eyJ1IjoiZGltYWRnbyIsImEiOiJjanYydDF2dTkwdnFzNDNwOXFuNzY4OGxnIn0.wnBvykpkR0RtWOp7bj74Yw'

# Cell

branch = 'dev'
bot_token = '5203882708:AAG3G_Y2oZSr-rMG2zoffDVtj3d0KkOFSts'   if branch == 'prod' else "5091011572:AAG4NfkC_zZjcsaAFkwLm4ZXOvhEqyLpQhY"


# Cell
main_path                       = Path(os.getenv("HOME"))
data_path                       = Path(main_path/'ssd/food')
reference_images_path           = Path(data_path/'reference_images')
fragment_reference_images_path  = Path(data_path/'fragment_reference_images')