# AUTOGENERATED! DO NOT EDIT! File to edit: 00_paths.ipynb (unless otherwise specified).

__all__ = ['mapbox_access_token', 'main_path', 'data_path', 'reserence_images_path']

# Cell
from pathlib import Path
import os

# Cell
Path.ls = lambda x: list(x.iterdir())

# Cell
mapbox_access_token = 'pk.eyJ1IjoiZGltYWRnbyIsImEiOiJjanYydDF2dTkwdnFzNDNwOXFuNzY4OGxnIn0.wnBvykpkR0RtWOp7bj74Yw'

# Cell
main_path              = Path(os.getenv("HOME"))
data_path              = Path(main_path/'data')
reserence_images_path  = Path(data_path/'reserence_images')