# AUTOGENERATED! DO NOT EDIT! File to edit: 00_nbs/00_paths.ipynb (unless otherwise specified).

__all__ = ['branch', 'bot_token', 'main_path', 'data_path', 'reference_images_path', 'fragment_reference_images_path']

# Cell
from pathlib import Path
import os

# Cell

branch = 'dev'
bot_token = '5203882708:AAG3G_Y2oZSr-rMG2zoffDVtj3d0KkOFSts'   if branch == 'prod' else "5091011572:AAG4NfkC_zZjcsaAFkwLm4ZXOvhEqyLpQhY"


# Cell
main_path                       = Path(os.getenv("HOME"))
data_path                       = Path(main_path/'data/food')
reference_images_path           = Path(data_path/'reference_images')
fragment_reference_images_path  = Path(data_path/'fragment_reference_images')