# AUTOGENERATED! DO NOT EDIT! File to edit: 00_qdrant.ipynb (unless otherwise specified).

__all__ = ['collection_name', 'dim', 'prod_client', 'dev_client', 'client']

# Cell
from .tools import *
from .paths import *
from .psql import *

import pandas as pd
import numpy as np
from tqdm import tqdm

from qdrant_client import QdrantClient
import qdrant_client
collection_name = "food_images"

# collection_name = "food_categories"



# Cell
dim = 768 #+ onehot.n_dim()
QdrantClient.get_collections = lambda self: [c['name'] for c in self.http.collections_api.get_collections().dict()['result']['collections']]
QdrantClient.collection_len = lambda self, name: self.http.collections_api.get_collection(name).dict()['result']['vectors_count']

# Cell
prod_client = QdrantClient(host='localhost', port=6335)
dev_client  = QdrantClient(host='localhost', port=6334)
client = prod_client if branch == "prod" else dev_client
