# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_nbs/00_paths.ipynb.

# %% auto 0
__all__ = ['branch', 'location', 'domain', 'local_data_path', 'docker_v_path', 'psql_backup_path', 'checkpoints_path',
           'reference_images_path', 'fragment_reference_images_path', 'test_path']

# %% ../00_nbs/00_paths.ipynb 1
from pathlib import Path
import os

# %% ../00_nbs/00_paths.ipynb 2
branch = 'dev'

if branch == 'prod':
    bot_token        = '5203882708:AAG3G_Y2oZSr-rMG2zoffDVtj3d0KkOFSts'  
    folder_name      = 'food_prod'
    env              = 'fprod'
       
if branch == 'dev':
    bot_token        = "5091011572:AAG4NfkC_zZjcsaAFkwLm4ZXOvhEqyLpQhY"
    folder_name      = 'food_dev'
    env              = 'f1'
    
location         = f'{folder_name}/code'
domain = 'https://dima.skynet.center'

# %% ../00_nbs/00_paths.ipynb 3
from mytools.paths import *
from mytools.tools import *

from segmentor.paths import checkpoints_path

# %% ../00_nbs/00_paths.ipynb 4
local_data_path = data_path/folder_name
docker_v_path = local_data_path/'docker_psql'
psql_backup_path = local_data_path/'psql_backup'


checkpoints_path = checkpoints_path


reference_images_path           = local_data_path/'reference_images'
fragment_reference_images_path  = local_data_path/'fragment_reference_images'

test_path                       =datasets_path/'mnogolasosya'
